init web pushes sdk
PushedLab/pushed-web-sdk pull request #1
Opened 2024-11-14 09:16 UTC by Goreglyad94

2024-11-14 16:00 UTC, Gimemor commented on src/config.js
> +    //ignore
А в каком случае может быть ошибка экспорта? Не лучше ли проверить что module существует, чем подавлять исключения?

2024-11-14 16:05 UTC, Gimemor commented on src/util/storage.js
> +        return self.localStorage ? self.localStorage.getItem(key) : this.cache[key];
Получается тут всегда будет мимо кэша доставать из localStorage?

2024-11-14 16:07 UTC, Gimemor commented on src/util/storage.js
> +            browser.storage.local.set({ [key]: value });
А зачем устанавливать значение в таком виде?  У расширения нет такого метода?
https://developer.mozilla.org/ru/docs/Web/API/Storage/setItem

2024-11-14 16:46 UTC, Gimemor commented on src/lib/sw.js
> +importScripts('https://pushed.ru/sw.js');
Не оч хорошо, надо занести в проект. Если потом уедет, то придется искать почему все отвалилось + там дериктива останова debugger в первой строке + есть же еще dev контур

2024-11-14 17:02 UTC, Gimemor commented on src/lib/pushed.js
> +        if (navigator.serviceWorker) {
ожидание воркера можно вынести в отдельную функцию, оно повторяется в setNotificationListener и в register

2024-11-14 17:05 UTC, Gimemor commented on src/lib/pushed.js
> +            if (!event.data && event.detail) {
можно в sw просто убедиться что данные всегда лежат в data

2024-11-14 17:08 UTC, Gimemor commented on src/lib/pushed.js
> +    Pushed.validateDeviceCredentials().catch((err) => {
А точно нужно валидировать здесь? Есть еще одна валидация в register.

2024-11-14 17:10 UTC, Gimemor commented on src/lib/pushed.d.ts
> +    export function isEnterpriseConfigured(): boolean;
такого метода нет

2024-11-14 17:11 UTC, Gimemor commented on src/lib/pushed.js
> +            let registration;
я бы немного поправил нейминг так как две регистрации - сервисворкера и в пушеде

2024-11-14 17:12 UTC, Gimemor commented on src/lib/pushed.js
> +            if (navigator.serviceWorker) {
ожидание воркера можно переиспользовать еще setNotificationListener

2024-11-14 17:13 UTC, Gimemor commented on src/lib/pushed.js
> +            if (!subscription) {
можно вынести создание подписки в отдельный метод чтоб было попроще читать

2024-11-14 17:13 UTC, Gimemor commented on src/lib/pushed.js
> +                    catch (e) {
возможно тут не стоит прям все ошибки игнорить

2024-11-15 07:50 UTC, Goreglyad94 commented on src/lib/pushed.js
> +                    catch (e) {
тут игнорить нужно. если любая ошибка, то будет регистрация нового девайса, и будет новый токен сгенерен

2024-11-15 07:52 UTC, Goreglyad94 commented on src/util/storage.js
> +        return self.localStorage ? self.localStorage.getItem(key) : this.cache[key];
удалил кэш экстьеншена

2024-11-15 07:53 UTC, Goreglyad94 commented on src/lib/sw.js
> +importScripts('https://pushed.ru/sw.js');
занес обратно

2024-11-15 08:00 UTC, Goreglyad94 commented on src/lib/pushed.js
> +    Pushed.validateDeviceCredentials().catch((err) => {
не уверен, что нужно. пока удалил

2024-11-15 08:00 UTC, Goreglyad94 commented on src/lib/pushed.d.ts
> +    export function isEnterpriseConfigured(): boolean;
удалил

2024-11-15 10:52 UTC, TimAlexeev requested changes

2024-11-15 10:52 UTC, TimAlexeev commented on src/lib/pushed.js
> +            else if (self.registration) {
пустая ветка кода, стоит убрать

2024-11-15 10:52 UTC, TimAlexeev commented on src/lib/pushed.js
> +            subscription = JSON.parse(JSON.stringify(subscription));
здесь хорошо бы дать пояснение, что происходит
если это глубокое копирование объекта, то нужно его записывать в другую переменную ( + учесть разные нюансы такого метода)
если что то другое, то пояснить, что именно

2024-11-15 10:52 UTC, TimAlexeev commented on src/lib/pushed.js
> +            if (!response.success) {
по сути эти два if можно объединить в 1, т.к одно и то же сообщение об ошибке

2024-11-15 10:52 UTC, TimAlexeev commented on src/lib/pushed.js
> +        if (!endpoint){
объединить два if в один

2024-11-15 10:52 UTC, TimAlexeev commented on src/lib/pushed.js
> +                    return reject(new Error('For Web Push on iOS 16.4+, you will first need to click the "Share" button -> "Aedd to Home Scren" before you can sign up for push notifications.'));
исправить опечатки -> Add to Home Screen

2024-11-15 10:52 UTC, TimAlexeev commented on src/lib/pushed.js
> +                if (/iPad|iPhone|iPod/.test(navigator.platform) || (navigator.platform === 'MacIntel' && navigator.maxTouchPoints > 1)) {
для читаемости лучше вынести в отдельный метод и оставить коммент, что метод делает
синтаксис jsDoc

```javascript
/**
 * Проверяем, с какого устройства зашел пользователь. Есть исключения в работе. 
 *
 * @param {string} plarform - Navigator.platform
 */
  validateUserPlatform(platform) {
   // ... 
  }
```

2024-11-15 10:52 UTC, TimAlexeev commented on src/lib/sw.js
> +                console.log(json)
все будет лететь в консоль - нужно ли нам это в проде? если нет, то убрать

2024-11-15 10:52 UTC, TimAlexeev commented on package.json
> +  "author": "Pushed",
вот тут нужна консультация Леши
точно ли MIT и правильно ли написан автор.

2024-11-15 10:59 UTC, Goreglyad94 commented on src/config.js
> +    //ignore
убрал

2024-11-15 11:01 UTC, Goreglyad94 commented on src/lib/pushed.js
> +            let registration;
поправил

2024-11-15 11:02 UTC, Goreglyad94 commented on src/util/api.js
> +        let options = {};
поправил

2024-11-15 11:03 UTC, Goreglyad94 commented on src/util/base64.js
> +        for (let i = 0; i < rawData.length; ++i) {
поправил

2024-11-15 11:05 UTC, Goreglyad94 commented on src/lib/pushed.js
> +                response = await api.post('/v2/web-push/auth-client', postData);
поправил

2024-11-15 11:06 UTC, Goreglyad94 commented on src/util/storage.js
> +                this.cache[key] = (await browser.storage.local.get(key))[key];
это все удалили, все что связано с isWebExtension

2024-11-15 11:07 UTC, Goreglyad94 commented on src/util/api.js
> +        let options = {};
добавил возврат из метода

2024-11-15 11:09 UTC, Goreglyad94 commented on src/lib/pushed.js
> +            subscription = JSON.parse(JSON.stringify(subscription));
сделал другую переменную

2024-11-15 11:10 UTC, Goreglyad94 commented on src/lib/pushed.js
> +        if (!endpoint){
объединил

2024-11-15 11:12 UTC, Goreglyad94 commented on src/lib/sw.js
> +                console.log(json)
убрал

2024-11-15 11:15 UTC, Goreglyad94 commented on src/lib/pushed.js
> +                if (/iPad|iPhone|iPod/.test(navigator.platform) || (navigator.platform === 'MacIntel' && navigator.maxTouchPoints > 1)) {
рефакторинг оставлю до следующего раза

2024-11-15 11:34 UTC, Goreglyad94 commented on src/config.js
> +    //ignore
вернул)
оказывается нужно. разберемся попож что с этим сделать

2024-11-15 11:35 UTC, Goreglyad94 commented on src/lib/pushed.js
> +            if (navigator.serviceWorker) {
рефакторинг оставлю до следующего раза

2024-11-15 11:35 UTC, Goreglyad94 commented on src/lib/pushed.js
> +            if (!subscription) {
рефакторинг оставлю до следующего раза

2024-11-15 12:37 UTC, merged